[package]
name = "divergence-arena"
version = "0.1.0"
edition = "2021"
description = "Guess 2/3 of the Average â€” Pinocchio BPF program"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
pinocchio = "0.10"
pinocchio-log = "0.3"
pinocchio-pubkey = "0.2"
pinocchio-system = "0.4"
